### PR TITLE
Due date extension nam

### PR DESCRIPTION
**Pull request by recluze**
I was in a hurry to get this done. So, I coded the backend. It's now possible for the instructor to allocate extension days through the backend. Requesting by the student is not possible through the frontend though at the moment. 

So, this fixes half of #9

### CODE REVIEW

**Comment by recluze** [comment]
If this is ok, let's merge and then I can comment on what I think needs to be done on the student's end.

**Comment by soachishti** [comment]
@recluze Bilal is working on this... he is currently testing his code.

**Comment by recluze** [comment]
No problem. He can continue working on the front-end part. You two review this code to just to see if you can find a problem.

**Comment by soachishti** [comment]
He has completed back-end and front-end part... he is pushing the code now.

However, your code looks fine to me... but let see if @BilalZaib have something for us.

**Comment by recluze** [comment]
Sure. If he has completed and it works fine, it should be ok to merge that.

**Pull request merged**
